a22207193/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('festivais/', include('festivais.urls')),
    path('articles/', include('articles.urls')),
    path('cursos/', include('cursos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.bandList_view, name='bandas_url'),
    path('band/<int:band_id>/', views.band_view, name='banda_url'),
    path('album/<int:album_id>/', views.album_view, name='album_url'),
    path('song/<int:song_id>/', views.song_view, name='song_url'),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('nova_banda/', views.nova_banda_view, name="nova_banda_url"),
    path('edita_banda/<int:band_id>/', views.edita_banda_view, name="edita_banda_url"),
    path('novo_album/<int:band_id>/', views.novo_album_view, name="novo_album_url"),
    path('edita_album/<int:album_id>/', views.edita_album_view, name="edita_album_url"),
    path('nova_musica/<int:album_id>/', views.nova_musica_view, name="nova_musica_url"),
    path('edita_musica/<int:song_id>/', views.edita_musica_view, name="edita_musica_url"),
]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('', views.index_view, name='index_url'),
    path('cinco_dias/', views.cinco_dias_view, name='cinco_dias_url'),
    path('api_meteo/', views.api_meteo_view, name='api_meteo_url'),
]

bandas/models.py
from django.db import models

class Band(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='bandas/', null=True, blank=True)
    info = models.TextField()
    biography = models.TextField(null=True, blank=True)
    yearFormation = models.PositiveIntegerField(blank=True)
    genre = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=100)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='bandas/', null=True, blank=True)
    releaseDate = models.DateField()
    label = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Song(models.Model):
    title = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    linkSpotify = models.URLField()
    duration = models.DurationField()
    lyrics = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

bandas/forms.py
from django import forms
from .models import Band, Album, Song


class bandForm(forms.ModelForm):
  class Meta:
    model = Band
    fields = '__all__'

    widgets = {
      'name': forms.TextInput(attrs={
          'placeholder':'Nome da banda',
      })
    }

    labels = {
      'name': 'Nome da Banda',
      'photo': 'Foto',
      'biography': 'Biografia',
      'yearFormation': 'Ano de formação',
      'genre': 'Genero'
    }

    help_texts = {
            'name': 'Insira o nome da banda.',
            'photo': 'Carregue uma foto da banda.',
            'info': 'Insira informações da banda.',
            'biography': 'Insira a biografia da banda.',
            'yearFormation': 'Insira o ano de formação da banda.',
            'genre': 'Insira o gênero musical da banda.'
        }

class albumForm(forms.ModelForm):
  class Meta:
    model = Album
    fields = '__all__'

    widgets = {
      'title': forms.TextInput(attrs={
          'placeholder':'Título do álbum',
      })
    }

    labels = {
      'title': 'Título do Álbum',
      'releaseDate': 'Ano de Lançamento',
      'band': 'Banda',
      'cover': 'Capa',
    }

    help_texts = {
            'title': 'Insira o título do álbum.',
            'band': 'Insira a banda que tem este álbum.',
            'cover': 'Carregue uma imagem do álbum.',
            'releaseDate': 'Insira a data de lançamento do álbum.',
            'label': 'Insira a label que lançou este álbum.'
        }

class songForm(forms.ModelForm):
  class Meta:
    model = Song
    fields = '__all__'

    widgets = {
      'title': forms.TextInput(attrs={
          'placeholder':'Título da música',
      })
    }

    labels = {
      'title': 'Título da Música',
      'lyrics': 'Letra',
      'duration': 'Duração',
      'linkSpotify': 'Link Spotify',
    }

    help_texts = {
            'title': 'Insira o título da música.',
            'album': 'Insira o àlbum que tem esta música.',
            'linkSpotify': 'Insira o link Spotify da música.',
            'lyrics': 'Insira a letra da música, se houver.',
            'duration': 'Insira a duração da música.',
        }

bandas/views.py
from django.shortcuts import render, redirect
from .models import Band, Album, Song
from django.contrib.auth import models
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from functools import wraps
from django.http import HttpResponseForbidden
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
from .forms import bandForm, albumForm, songForm



def album_view(request, album_id):
    album = Album.objects.get(pk=album_id)
    context = {'album': album}
    return render(request, 'bandas/album.html', context)

def band_view(request, band_id):
    band = Band.objects.get(pk=band_id)
    albums = band.album_set.all()
    context = {'band': band, 'albums': albums}
    return render(request, 'bandas/band.html', context)

def song_view(request, song_id):
    song = Song.objects.get(pk=song_id)
    context = {'song': song}
    return render(request, 'bandas/song.html', context)

def bandList_view(request):
    bands = Band.objects.all()
    context = {'bands': bands}
    return render(request, 'bandas/bandList.html', context)

def registo_view(request):
    if request.method == "POST":
        models.User.objects.create_user(
            username=request.POST['username'],
            email=request.POST['email'],
            first_name=request.POST['nome'],
            last_name=request.POST['apelido'],
            password=request.POST['password']
        )
        return redirect('bandas:login')

    return render(request, 'bandas/registo.html')


def login_view(request):
    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user:
            login(request, user)
            return redirect('bandas:bandas_url')
        else:
            render(request, 'bandas/login.html', {
                'mensagem':'Credenciais inválidas'
            })

    return render(request, 'bandas/login.html')

def logout_view(request):
    logout(request)
    return redirect('bandas:login')

def group_required(*group_names):
    def in_groups(user):
        if user.is_authenticated:
            if bool(user.groups.filter(name__in=group_names)) | user.is_superuser:
                return True
        raise PermissionDenied
    return user_passes_test(in_groups)

#Bandas

@group_required('Editor de Bandas', 'Admin')
def nova_banda_view(request):

    form = bandForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('bandas:bandas_url')

    context = {'form': form}
    return render(request, 'bandas/nova_banda.html', context)

@group_required('Editor de Bandas', 'Admin')
def edita_banda_view(request, band_id):
    band = Band.objects.get(pk=band_id)

    if request.method == 'POST':
        form = bandForm(request.POST, request.FILES, instance=band)
        if form.is_valid():
            form.save()
            return redirect('bandas:banda_url', band.id)
    else:
        form = bandForm(instance=band)

    context = {'form': form, 'band': band}
    return render(request, 'bandas/edita_banda.html', context)

@group_required('Admin')
def apaga_band_view(request, band_id):
    band = Band.objects.get(pk=band_id)
    context = {'band': band}
    band.delete()
    return render(request, 'bandas/band.html', context)

#Albuns

@group_required('Editor de Bandas', 'Admin')
def novo_album_view(request, band_id):
    band = Band.objects.get(pk=band_id)

    if request.method == 'POST':
        form = albumForm(request.POST, request.FILES)
        if form.is_valid():
            album = form.save(commit=False)
            album.band = band
            album.save()
            return redirect('bandas:band_url', band.name)
    else:
        form = albumForm(initial={'band': band})

    context = {'form': form, 'band':band}
    return render(request, 'bandas/novo_album.html', context)

@group_required('Editor de Bandas', 'Admin')
def edita_album_view(request, album_id):
    album = Album.objects.get(pk=album_id)
    band = album.band

    if request.method == 'POST':
        form = albumForm(request.POST, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:album_url', album.title)
    else:
        form = albumForm(instance=album)

    context = {'form': form, 'album': album, 'band': band}
    return render(request, 'bandas/edita_album.html', context)

@group_required('Admin')
def apaga_album_view(request, album_id):
    album = Album.objects.get(pk=album_id)
    context = {'album': album}
    album.delete()
    return render(request, 'bandas/album.html', context)

#musicas

@group_required('Editor de Bandas', 'Admin')
def nova_musica_view(request, album_id):
    album = Album.objects.get(pk=album_id)

    if request.method == 'POST':
        form = songForm(request.POST, request.FILES)
        if form.is_valid():
            song = form.save(commit=False)
            song.album = album
            song.save()
            return redirect('bandas:album_url', album.id)
    else:
        form = songForm(initial={'album': album})

    context = {'form': form, 'album':album}
    return render(request, 'bandas/nova_musica.html', context)

@group_required('Editor de Bandas', 'Admin')
def edita_musica_view(request, song_id):
    song = Song.objects.get(pk=song_id)
    album = song.album

    if request.method == 'POST':
        form = songForm(request.POST, request.FILES, instance=song)
        if form.is_valid():
            form.save()
            return redirect('bandas:song_url', song.id)
    else:
        form = songForm(instance=song)

    context = {'form': form, 'album': album, 'song': song}
    return render(request, 'bandas/edita_musica.html', context)

@group_required('Admin')
def apaga_musica_view(request, song_id):
    song = Song.objects.get(pk=song_id)
    context = {'song': song}
    song.delete()
    return render(request, 'bandas/song.html', context)

bandas/templates/bandas/album.html
{% extends 'bandas/layout.html' %}

{% block content %}



<div class="album-details">
    <h2>{{ album.title }}</h2>
    <img src="{{ album.cover.url }}" alt="{{ album.title }} Cover">
    <p>Data de Lançamento: {{ album.releaseDate }}</p>
    <p>Gravadora: {{ album.label }}</p>

    <div id="listaMusicas">
    <h3>Lista de Músicas</h3>
    <ul>
        {% for musica in album.song_set.all %}
            <li class = "song"><a href="{% url 'bandas:song_url' musica.id %}"> {{ musica.title }}   </a>

            {% if musica.lyrics %}

                <i class="fa-regular fa-comments"></i>
            {% endif %}

            </li>
        {% endfor %}
    </ul>

    </div>

    <a href="{% url 'bandas:edita_album_url' album.id %}"><button>Editar Álbum</button></a>
    <a href="{% url 'bandas:nova_musica_url' album.id %}"><button>Adicionar Música</button></a>
</div>
{% endblock %}

bandas/templates/bandas/band.html
{% extends 'bandas/layout.html' %}

{% block content %}
<div class="band-details">
    <h2>{{ band.name }}</h2>
    <img src="{{ band.photo.url }}" alt="{{ band.name }}">
    <p>{{ band.info }}</p>
    <p class='bandaBiografia'>{{ band.biography }}</p>
    <h3>Álbuns</h3>
    <ul>
        {% for album in albums %}
        <li><a href="{% url 'bandas:album_url' album.id %}">{{ album.title }}</a></li>
        {% endfor %}
    </ul>

    <a href="{% url 'bandas:novo_album_url' band.id %}"><button>Adicionar Álbum</button></a>
    <a href="{% url 'bandas:edita_banda_url' band.id %}"><button>Editar Banda</button></a>
</div>
{% endblock %}

bandas/templates/bandas/bandList.html
{% extends 'bandas/layout.html' %}

{% block content %}
<div class="band-list">
    <h2>Lista de Bandas</h2>
    <ul>
        {% for banda in bands %}
        <li>
            <h3>{{ banda.name }}</h3>
            <img src="{{ banda.photo.url }}" alt="{{ banda.name }}">
            <p>{{ banda.info }}</p>
            <a href="{% url 'bandas:banda_url' banda.id %}">Ver Detalhes</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'bandas:nova_banda_url' %}"><button>Adicionar Banda</button></a>
</div>
{% endblock %}

bandas/templates/bandas/edita_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Album</h3>

    <form action="{% url 'bandas:edita_album_url' album.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bandas/templates/bandas/edita_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Banda</h3>

    <form action="{% url 'bandas:edita_banda_url' band.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bandas/templates/bandas/edita_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Musica</h3>

    <form action="{% url 'bandas:edita_musica_url' song.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bandas/templates/bandas/html5-css.html
<h3>Seletores CSS</h3>
<p>CSS (Cascading Style Sheets) é uma linguagem de estilo usada para descrever a apresentação de um documento escrito em HTML ou XML.</p>
<table>
  <tr>
    <th>Tipo de Seletor</th>
    <th>Usado</th>
    <th>Comentário</th>
  </tr>
  <tr>
    <td>Classe</td>
    <td><i class="material-icons">check</i></td>
    <td>Usado para estilizar elementos com atributos de classe.</td>
  </tr>
  
</table>

<h3>Combinadores de Seletores</h3>
<table>
  <tr>
    <th>Combinador</th>
    <th>Usado</th>
    <th>Comentário</th>
  </tr>
  <tr>
    <td>Descendente</td>
    <td><i class="material-icons">check</i></td>
    <td>Estiliza elementos descendentes de um elemento pai.</td>
  </tr>
  
</table>
---

bandas/templates/bandas/layout.html
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'bandas/styles.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/73896b70fb.js" crossorigin="anonymous"></script>

    <title>{% block title %}Bandas{% endblock %}</title>


</head>
<body>
    <header>
        <h1 id="link"><a href="{% url 'bandas:bandas_url' %}"><i class="fa-solid fa-drum"></i> Bandas</a></h1>

        <div id="user-links">
            {% if user.is_authenticated %}
                <span>Olá, {{ user.username }}!</span>
                <a href="{% url 'bandas:logout' %}"><button>Logout</button></a>
            {% else %}
                <a href="{% url 'bandas:login' %}"><button>Login</button></a>
                <a href="{% url 'bandas:registo' %}"><button>Register</button></a>
            {% endif %}



        </div>

    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>

    </footer>
</body>
</html>

bandas/templates/bandas/login.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Login</h3>

    {% if mensagem %}
      <p>mensagem: {{ mensagem }}</p>
    {% endif %}
    <form action="{% url 'bandas:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username..">
      <input type="password" name="password" placeholder="Password..">
      <input type="submit">
    </form>

    <a href="{% url 'reset_password' %}" class="nav-link">
        Recuperar Palavra-chave
    </a>

{% endblock %}

bandas/templates/bandas/nova_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Nova Banda</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Banda">
    </form>

{% endblock %}

bandas/templates/bandas/nova_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Novo Banda</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Musica">
    </form>

{% endblock %}

bandas/templates/bandas/novo_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Novo Album</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Album">
    </form>

{% endblock %}

bandas/templates/bandas/registo.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Registo</h3>

    <form action="{% url 'bandas:registo' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="O seu username..">
      <input type="text" name="nome" placeholder="O seu nome..">
      <input type="text" name="apelido" placeholder="O seu apelido..">
      <input type="email" name="email" placeholder="O seu email..">
      <input type="password" name="password" placeholder="Defina a sua password..">
      <input type="submit" value="Criar">
    </form>

    <a href="{% url 'bandas:login' %}">Cancelar</a>

{% endblock %}

bandas/templates/bandas/song.html
{% extends 'bandas/layout.html' %}

{% block content %}


<div>
    <h2>{{ song.title }}</h2>
    <p>Duração: {{ song.duration }}</p>
    <p>Link Spotify: <a href="{{ song.linkSpotify }}">{{ song.linkSpotify }}</a></p>

    {% if song.lyrics %}
        <p>{{ song.lyrics }}</p>
    {% endif %}

    <a href="{% url 'bandas:edita_musica_url' song.id %}"><button>Editar Música</button></a>


</div>
{% endblock %}