a22207193/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('festivais/', include('festivais.urls')),
    path('articles/', include('articles.urls')),
    path('cursos/', include('cursos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
]

cursos/urls.py
from django.urls import path
from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.home_view, name='homecursos_url'),
    path('<int:curso_id>/', views.curso_view, name='curso_url'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name='disciplina_url'),
    path('projeto/<str:projeto_nome>/', views.projeto_view, name='projeto_url'),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('novo_curso/', views.novo_curso_view, name="novo_curso_url"),
    path('edita_curso/<int:curso_id>/', views.edita_curso_view, name="edita_curso_url"),
    path('nova_disciplina/<int:curso_id>/', views.nova_disciplina_view, name="nova_disciplina_url"),
    path('edita_disciplina/<int:disciplina_id>/', views.edita_disciplina_view, name="edita_disciplina_url"),
    path('novo_projeto/<int:disciplina_id>/', views.novo_projeto_view, name="novo_projeto_url"),
    path('edita_projeto/<int:projeto_id>/', views.edita_projeto_view, name="edita_projeto_url"),
    path('novo_docente/<int:disciplina_id>/', views.novo_docente_view, name="novo_docente_url"),
    path('edita_docente/<int:docente_id>/<int:disciplina_id>/', views.edita_docente_view, name="edita_docente_url"),
]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('', views.index_view, name='index_url'),
    path('cinco_dias/', views.cinco_dias_view, name='cinco_dias_url'),
    path('api_meteo/', views.api_meteo_view, name='api_meteo_url'),
]

cursos/models.py
from django.db import models

class Curso(models.Model):
    nome = models.CharField(max_length=100)
    apresentacao = models.TextField()
    objetivos = models.TextField()
    competencias = models.TextField()
    disciplinas = disciplinas = models.ManyToManyField('Disciplina', related_name='cursos')

    def __str__(self):
        return self.nome


class AreaCientifica(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length=100)
    ano = models.IntegerField()
    semestre = models.CharField(max_length=20)
    ects = models.IntegerField()
    curricularIUnitCode = models.CharField(max_length=100)
    areaCientifica = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome


class Projeto(models.Model):
    nome = models.CharField(max_length=150)
    descricao = models.TextField()
    conceitosAplicados = models.TextField()
    tecnologiasUsadas = models.TextField()
    disciplina = models.OneToOneField(Disciplina, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='projeto_images', null=True, blank=True)
    linkVideo = models.URLField(null=True, blank=True)
    linkGithub = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.nome


class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=100)
    projetos = models.ManyToManyField(Projeto)

    def __str__(self):
        return self.nome


class Docente(models.Model):
    nome = models.CharField(max_length=100)
    disciplinas = models.ManyToManyField(Disciplina)

    def __str__(self):
        return self.nome

cursos/forms.py
from django import forms
from .models import Curso, Disciplina, Projeto, Docente, LinguagemProgramacao, AreaCientifica


class cursoForm(forms.ModelForm):
  class Meta:
    model = Curso
    fields = '__all__'

    widgets = {
      'nome': forms.TextInput(attrs={
          'placeholder':'Nome do Curso',

      })
    }

    labels = {
        'nome': 'Nome do Curso',
        'apresentacao': 'Apresentação sobre o Curso',
        'objetivos': 'Objetivos do Curso',
        'competencias': 'Competencias do Curso',
        'disciplinas': 'Disciplinas do Curso',
    }

    help_texts = {

        }

class disciplinaForm(forms.ModelForm):
  class Meta:
    model = Disciplina
    fields = '__all__'

    widgets = {
      'nome': forms.TextInput(attrs={
          'placeholder':'Nome da disciplina',
      })
    }

    labels = {
      'nome': 'Nome',
      'ano': 'Ano',
      'semestre': 'Semestre',
      'ects': 'Créditos',
      'curricularIUnitCode': 'Codigo Curricular',
      'areaCientifica': 'Area Cientifica',
      'curso': 'Curso',
    }

    help_texts = {

        }

class projetoForm(forms.ModelForm):
  class Meta:
    model = Projeto
    fields = '__all__'

    widgets = {
      'title': forms.TextInput(attrs={
          'placeholder':'Título da música',
      })
    }

    labels = {
      'nome': 'Nome do Projeto',
      'descricao': 'Descrição',
      'conceitosAplicados': 'Conceitos Aplicados',
      'tecnologiasUsadas': 'Tecnologias Usadas',
      'disciplina': 'Disciplina',
    }

    help_texts = {

        }


class linguagemProgramacaoForm(forms.ModelForm):
  class Meta:
    model = LinguagemProgramacao
    fields = '__all__'

    widgets = {
      'nome': forms.TextInput(attrs={
          'placeholder':'Nome da linguagem',
      })
    }

    labels = {
      'nome': 'Nome da linguagem',
    }

    help_texts = {

        }


class docenteForm(forms.ModelForm):
  class Meta:
    model = Docente
    fields = '__all__'

    widgets = {
      'nome': forms.TextInput(attrs={
          'placeholder':'Nome do docente',
      })
    }

    labels = {
      'nome': 'Nome do Docente',
    }

    help_texts = {

        }


class areaCientificaForm(forms.ModelForm):
  class Meta:
    model = AreaCientifica
    fields = '__all__'

    widgets = {
      'nome': forms.TextInput(attrs={
          'placeholder':'Nome da área cienfífica',
      })
    }

    labels = {
      'nome': 'Nome da área cienfífica',
    }

    help_texts = {

        }

cursos/views.py
from django.shortcuts import render, redirect
from .models import Curso, AreaCientifica, Disciplina, Projeto, LinguagemProgramacao, Docente
from django.contrib.auth import models
from django.contrib.auth import authenticate, login, logout
from functools import wraps
from django.http import HttpResponseForbidden
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
from .forms import cursoForm, disciplinaForm, projetoForm, areaCientificaForm, docenteForm, linguagemProgramacaoForm

def home_view(request):

    cursos = Curso.objects.all()
    context = {
        'cursos': cursos,
        }

    return render(request, 'cursos/homecursos.html', context)

def curso_view(request, curso_id):

    curso = Curso.objects.get(pk=curso_id)
    disciplinas = Disciplina.objects.filter(curso=curso)
    context = {
        'curso': curso,
        'disciplinas': disciplinas,
        }

    return render(request, 'cursos/curso.html', context)

def disciplina_view(request, disciplina_id):

    disciplina = Disciplina.objects.get(pk=disciplina_id)
    try:
        projeto = Projeto.objects.get(disciplina=disciplina)
    except Projeto.DoesNotExist:
        projeto = None

    linguagens = LinguagemProgramacao.objects.filter(projetos=projeto)

    docentes = Docente.objects.filter(disciplinas=disciplina)

    context = {
        'disciplina': disciplina,
        'projeto': projeto,
        'linguagens': linguagens,
        'docentes': docentes
        }

    return render(request, 'cursos/disciplina.html', context)


def projeto_view(request, projeto_nome):

    projeto = Projeto.objects.get(nome=projeto_nome)
    linguagens = LinguagemProgramacao.objects.filter(projetos=projeto)

    context = {
        'projeto': projeto,
        'linguagens': linguagens,
        }

    return render(request, 'cursos/projeto.html', context)


def registo_view(request):
    if request.method == "POST":
        models.User.objects.create_user(
            username=request.POST['username'],
            email=request.POST['email'],
            first_name=request.POST['nome'],
            last_name=request.POST['apelido'],
            password=request.POST['password']
        )
        return redirect('cursos:login')

    return render(request, 'cursos/registo.html')


def login_view(request):
    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user:
            login(request, user)
            return redirect('cursos:homecursos_url')
        else:
            render(request, 'cursos/login.html', {
                'mensagem':'Credenciais inválidas'
            })

    return render(request, 'cursos/login.html')

def logout_view(request):
    logout(request)
    return redirect('cursos:login')


def group_required(*group_names):
    def in_groups(user):
        if user.is_authenticated:
            if bool(user.groups.filter(name__in=group_names)) | user.is_superuser:
                return True
        raise PermissionDenied
    return user_passes_test(in_groups)



#Curso

@group_required('Editor de Cursos', 'Admin')
def novo_curso_view(request):

    form = cursoForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('cursos:homecursos_url')

    context = {'form': form}
    return render(request, 'cursos/novo_curso.html', context)

@group_required('Editor de Cursos', 'Admin')
def edita_curso_view(request, curso_id):
    curso = Curso.objects.get(pk=curso_id)

    if request.method == 'POST':
        form = cursoForm(request.POST, request.FILES, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('cursos:curso_url', curso.name)
    else:
        form = cursoForm(instance=curso)

    context = {'form': form, 'curso': curso}
    return render(request, 'cursos/edita_curso.html', context)

@group_required('Admin')
def apaga_curso_view(request, curso_id):
    curso = Curso.objects.get(pk=curso_id)
    context = {'curso': curso}
    curso.delete()
    return render(request, 'cursos/homecursos.html', context)

#Disciplinas

@group_required('Editor de Cursos', 'Admin')
def nova_disciplina_view(request, curso_id):
    curso = Curso.objects.get(pk=curso_id)

    if request.method == 'POST':
        form = disciplinaForm(request.POST, request.FILES)
        if form.is_valid():
            disciplina = form.save(commit=False)
            disciplina.curso = curso
            disciplina.save()
            return redirect('cursos:curso_url', curso.id)
    else:
        form = disciplinaForm(initial={'curso': curso})

    context = {'form': form, 'curso':curso}
    return render(request, 'cursos/nova_disciplina.html', context)

@group_required('Editor de Cursos', 'Admin')
def edita_disciplina_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(pk=disciplina_id)
    curso = disciplina.curso

    if request.method == 'POST':
        form = disciplinaForm(request.POST, request.FILES, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('cursos:disciplina_url', disciplina.id)
    else:
        form = disciplinaForm(instance=disciplina)

    context = {'form': form, 'disciplina': disciplina, 'curso': curso}
    return render(request, 'cursos/edita_disciplina.html', context)

@group_required('Admin')
def apaga_disciplina_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(pk=disciplina_id)
    context = {'disciplina': disciplina}
    disciplina.delete()
    return render(request, 'cursos/disciplina.html', context)

#Projetos

@group_required('Editor de Cursos', 'Admin')
def novo_projeto_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(pk=disciplina_id)

    if request.method == 'POST':
        form = projetoForm(request.POST, request.FILES)
        if form.is_valid():
            projeto = form.save(commit=False)
            projeto.disciplina = disciplina
            projeto.save()
            return redirect('cursos:disciplina_url', disciplina.id)
    else:
        form = projetoForm(initial={'disciplina': disciplina})

    context = {'form': form, 'disciplina': disciplina}
    return render(request, 'cursos/novo_projeto.html', context)

@group_required('Editor de Cursos', 'Admin')
def edita_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(pk=projeto_id)
    disciplina = projeto.disciplina

    if request.method == 'POST':
        form = projetoForm(request.POST, request.FILES, instance=projeto)
        if form.is_valid():
            form.save()
            return redirect('cursos:projeto_url', projeto.nome)
    else:
        form = projetoForm(instance=projeto)

    context = {'form': form, 'projeto': projeto, 'disciplina': disciplina}
    return render(request, 'cursos/edita_projeto.html', context)

@group_required('Admin')
def apaga_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(pk=projeto_id)
    context = {'projeto': projeto}
    projeto.delete()
    return render(request, 'cursos/projeto.html', context)


#Docentes

@group_required('Editor de Cursos', 'Admin')
def novo_docente_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(pk=disciplina_id)

    if request.method == 'POST':
        form = docenteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cursos:disciplina_url', disciplina.id)
    else:
        form = docenteForm(initial={'disciplina': disciplina})

    context = {'form': form, 'disciplina':disciplina}
    return render(request, 'cursos/novo_docente.html', context)

@group_required('Editor de Cursos', 'Admin')
def edita_docente_view(request, docente_id, disciplina_id):
    docente = Docente.objects.get(pk=docente_id)
    disciplinas = docente.disciplinas
    disciplina = Disciplina.objects.get(pk=disciplina_id)

    if request.method == 'POST':
        form = docenteForm(request.POST, request.FILES, instance=docente)
        if form.is_valid():
            form.save()
            return redirect('cursos:disciplina_url', disciplina.id)
    else:
        form = docenteForm(instance=docente)

    context = {'form': form, 'docente': docente, 'disciplinas': disciplinas, 'disciplina': disciplina}
    return render(request, 'cursos/edita_docente.html', context)

@group_required('Admin')
def apaga_docente_view(request, docente_id):
    docente = Docente.objects.get(pk=docente_id)
    context = {'docente': docente}
    docente.delete()
    return render(request, 'cursos/disciplina.html', context)

cursos/templates/cursos/curso.html
{% extends 'cursos/layout.html' %}

{% block content %}

<div><h2>{{ curso.nome }}</h2></div>

<div class="curso-details">

    <p><strong>Apresentação: </strong>{{ curso.apresentacao }}</p>

    <p><strong>Objetivos: </strong>{{ curso.objetivos }}</p>

    <p><strong>Competências: </strong>{{ curso.competencias }}</p>

</div>

<div>
    <h3>Disciplinas</h3>
    <ul>
        {% for disciplina in disciplinas %}
        <li><a href="{% url 'cursos:disciplina_url' disciplina.id %}">{{ disciplina.nome }}</a></li>
        {% endfor %}

        <a href="{% url 'cursos:nova_disciplina_url' curso.id %}">
            <button class = "add_editbutton">
                Nova Disciplina
            </button>
        </a>
    </ul>

    <a href="{% url 'cursos:edita_curso_url' curso.id %}">
        <button class = "add_editbutton">
            Editar Curso
        </button>
    </a>
</div>
{% endblock %}

cursos/templates/cursos/disciplina.html
{% extends 'cursos/layout.html' %}

{% block content %}
<div class="disciplina-details">
    <h2>{{ disciplina.nome }}</h2>
    <p>Ano: {{ disciplina.ano }}</p>
    <p>Semestre: {{ disciplina.semestre }}</p>
    <p>Ects: {{ disciplina.ects }}</p>
    <h3>Projetos</h3>

    {% if projeto %}
        <ul>

            <li><a href="{% url 'cursos:projeto_url' projeto.nome %}">{{ projeto.nome }}</a></li>

            {% for linguagem in linguagens %}
                <li>{{ linguagem.nome }}</a></li>
            {% endfor %}

        </ul>

    {% endif %}

    <a href="{% url 'cursos:novo_projeto_url' disciplina.id %}">
        <button class = "add_editbutton">
            Novo Projeto
        </button>
    </a>

    <h3>Docentes</h3>
    <ul>
        {% for docente in docentes %}
            <li>{{ docente.nome }}</a></li>
            <a href="{% url 'cursos:edita_docente_url' docente.id disciplina.id %}"><button>Edita Docente</button></a>
        {% endfor %}
    </ul>

    <div>
        <a href="{% url 'cursos:novo_docente_url' disciplina.id %}">
            <button class = "add_editbutton">
                Novo Docente
            </button>
        </a>
    </div>

    <div>
        <a href="{% url 'cursos:edita_disciplina_url' disciplina.id %}">
            <button class = "add_editbutton">
                Editar Disciplina
            </button>
        </a>
    </div>
</div>
{% endblock %}

cursos/templates/cursos/edita_curso.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Edita Curso</h3>

    <form action="{% url 'cursos:edita_curso_url' curso.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

cursos/templates/cursos/edita_disciplina.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Edita Disciplina</h3>

    <form action="{% url 'cursos:edita_disciplina_url' disciplina.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

cursos/templates/cursos/edita_projeto.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Edita Projeto</h3>

    <form action="{% url 'cursos:edita_projeto_url' projeto.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

cursos/templates/cursos/homecursos.html
{% extends 'cursos/layout.html' %}

{% block content %}
<div>
    <h2>Lista de Cursos</h2>
    <ul>
        {% for curso in cursos %}
        <li>
            <h3>{{ curso.nome }}</h3>
            <p>{{ curso.content }}</p>
            <a href="{% url 'cursos:curso_url' curso.id %}">Ver Detalhes</a>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'cursos:novo_curso_url' %}">
        <button class = "add_editbutton">
            Adicionar Curso
        </button>
    </a>
</div>
{% endblock %}

cursos/templates/cursos/layout.html
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Cursos{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'cursos/styles.css' %}">

</head>
<body>
    <header>
        <h1 id="user-links"><a href="{% url 'cursos:homecursos_url' %}">Cursos</a></h1>

        <div id="user-links">
            {% if user.is_authenticated %}
                <span>Olá, {{ user.username }}!</span>
                <a href="{% url 'cursos:logout' %}"><button>Logout</button></a>
            {% else %}
                <a href="{% url 'cursos:login' %}"><button>Login</button></a>
                <a href="{% url 'cursos:registo' %}"><button>Register</button></a>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
            <p>© 2024 Cursos. José Vale.</p>
    </footer>
</body>
</html>

cursos/templates/cursos/login.html
{% extends 'cursos/layout.html' %}

{% block content %}

    <form class="form" action="{% url 'cursos:login' %}" method="post">
      {% csrf_token %}
      <p class="form-title">Sign in to your account</p>

      <div class="input-container">
        <input type="text" name="username" placeholder="Enter username" required>
        <span></span>
      </div>

      <div class="input-container">
        <input type="password" name="password" placeholder="Enter password" required>
      </div>

      <button type="submit" class="submit">Sign in</button>


      <p class="forgot-password">
        <a href="{% url 'reset_password' %}">Recuperar Palavra-chave</a>
      </p>
    </form>



{% endblock %}

cursos/templates/cursos/nova_disciplina.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Nova Disciplina</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Disciplina">
    </form>

{% endblock %}

cursos/templates/cursos/novo_curso.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Novo Curso</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Curso">
    </form>

{% endblock %}

cursos/templates/cursos/novo_docente.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Novo Docente</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Docente">
    </form>

{% endblock %}

cursos/templates/cursos/novo_projeto.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Novo Projeto</h3>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar Projeto">
    </form>

{% endblock %}

cursos/templates/cursos/projeto.html
{% extends 'cursos/layout.html' %}

{% block content %}
<div class="projeto-details">
    <h2>{{ projeto.nome }}</h2>

    {% if projeto.imagem %}
        <img src="{{ projeto.imagem.url }}" alt="{{ projeto.nome }}">
    {% endif %}
    <p>Descrição: {{ projeto.descricao }}</p>
    <p>Conceitos aplicados: {{ projeto.conceitosAplicados }}</p>
    <p>Tecnologias Usadas: {{ projeto.tecnologiasUsadas }}</p>



    <a href="{% url 'cursos:edita_projeto_url' projeto.id %}">
        <button class = "add_editbutton">
            Editar Projeto
        </button>
    </a>


</div>
{% endblock %}

cursos/templates/cursos/registo.html
{% extends 'cursos/layout.html' %}

{% block content %}
    <h3>Registo</h3>

    <form action="{% url 'cursos:registo' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="O seu username..">
      <input type="text" name="nome" placeholder="O seu nome..">
      <input type="text" name="apelido" placeholder="O seu apelido..">
      <input type="email" name="email" placeholder="O seu email..">
      <input type="password" name="password" placeholder="Defina a sua password..">
      <input type="submit" value="Criar">
    </form>

    <a href="{% url 'cursos:login' %}">Cancelar</a>

{% endblock %}