a22207193/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('festivais/', include('festivais.urls')),
    path('articles/', include('articles.urls')),
    path('cursos/', include('cursos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
]

festivais/urls.py
from django.urls import path
from . import views

app_name = 'festivais'

urlpatterns = [
    path('festivais/', views.festivais, name='festivais'),
    path('festival/<int:festival_id>/', views.festival, name='festival')
]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('', views.index_view, name='index_url'),
    path('cinco_dias/', views.cinco_dias_view, name='cinco_dias_url'),
    path('api_meteo/', views.api_meteo_view, name='api_meteo_url'),
]

festivais/models.py
from django.db import models

class Localizacao(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nome}"


class Banda(models.Model):
    nome = models.CharField(max_length=100)
    genero = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Festival(models.Model):
    nome = models.CharField(max_length=100)
    localizacao = models.ForeignKey(Localizacao, on_delete=models.CASCADE)
    bandas = models.ManyToManyField(Banda)
    data_inicio = models.DateField()
    data_fim = models.DateField()
    imagem = models.ImageField()
    site = models.URLField(blank=True)

    def __str__(self):
        return self.nome

festivais/views.py
from django.shortcuts import render
from .models import Festival, Localizacao

def festivais(request):
    festivais = Festival.objects.all()
    localizacoes = Localizacao.objects.all()
    context = {'festivais': festivais, 'localizacoes': localizacoes}
    return render(request, 'festivais/festivais.html', context)

def festival(request, festival_id):
    festival = Festival.objects.get(pk=festival_id)
    context = {'festival': festival}
    return render(request, 'festivais/festival.html', context)

festivais/templates/festivais/festivais.html
{% extends 'festivais/layout.html' %}

{% block content %}
    <h2>Festivais</h2>
    {% for localizacao in localizacoes %}
        <h3>{{ localizacao.nome }}</h3>
        <ul>
            {% for festival in localizacao.festival_set.all %}
                <ul>
                    <strong><a href="{% url 'festivais:festival' festival.id %}">{{ festival.nome }}</a></strong>
                    <br></br>
                    Bandas -

                    {% for banda in festival.bandas.all %}
                        {{ banda.nome }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}

                </ul>
            {% endfor %}
        </ul>
    {% endfor %}
{% endblock %}

festivais/templates/festivais/festival.html
{% extends 'festivais/layout.html' %}

{% block content %}
    <h2>{{ festival.nome }}</h2>
    <p><strong>Localização:</strong> {{ festival.localizacao }}</p>
    <p><strong>Data de Início:</strong> {{ festival.data_inicio }}</p>
    <p><strong>Data de Fim:</strong> {{ festival.data_fim }}</p>

    <h3>Bandas:</h3>
    <ul>
        {% for banda in festival.bandas.all %}
            <li>{{ banda.nome }} - Gênero: {{ banda.genero }}</li>
        {% endfor %}
    </ul>

    {% if festival.imagem %}
    <img src="{{ festival.imagem.url }}" alt="{{ festival.nome }}" style="max-width: 300px;">
    {% else %}
    <p>Imagem indisponível para este festival.</p>
    {% endif %}
    <br></br>

    <a href="{% url 'festivais:festivais' %}">Voltar para a lista de festivais</a>
{% endblock %}

festivais/templates/festivais/layout.html
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Festivais{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Festivais</h1>
    </header>

    {% block content %}

    {% endblock %}

    <footer>
        <p>2024</p>
    </footer>
</body>
</html>